[package]
name = "webserver"
version = "0.1.0"
authors = ["Hicham Azimani <hicham.azimani@outlook.com>"]
edition = "2021"
#build = "build.rs"
autotests = false
description = "Simple REST webserver"
license = "MIT"
repository = "https://github.com/AzHicham/webserver.git"
keywords = [ "webserver", "rest" ]
categories = [ "application" ]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = []

[features]
default = []

[dependencies]
config = "0.13"
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
tracing = { version = "0.1", features = ["std", "release_max_level_info"] }
static_assertions = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
tokio = { version = "1.14.0", features = [ "sync", "rt", "rt-multi-thread", "macros", "process" ] }
num_cpus = "1"
lazy_static = "1"
rocket = { version = "0.5.0-rc.2", features = ["serde_json", "json"] }
anyhow = "1"

[profile.dev]
opt-level = 1
codegen-units = 16

[profile.release]
opt-level = 3
debug = true
lto = true
codegen-units = 1
panic = 'unwind'

[[bin]]
name = "webserver"
path = "src/main.rs"
